## Variables in the Dataset 
 
  - "subject": id of subjects      
  - "activity": type of activity subject performed while measurement was taken: walking, walking upstairs, walking downstairs, sitting, standing, laying
  - "t_body_acc_mean_x"                      
  - "t_body_acc_mean_y"                       
  - "t_body_acc_mean_z"                       
  - "t_gravity_acc_mean_x"                   
  - "t_gravity_acc_mean_y"                    
  - "t_gravity_acc_mean_z"                    
  - "t_body_acc_jerk_mean_x"                 
  - "t_body_acc_jerk_mean_y"                  
  - "t_body_acc_jerk_mean_z"                  
  - "t_body_gyro_mean_x"                     
  - "t_body_gyro_mean_y"                      
  - "t_body_gyro_mean_z"                      
  - "t_body_gyro_jerk_mean_x"                
  - "t_body_gyro_jerk_mean_y"                 
  - "t_body_gyro_jerk_mean_z"                 
  - "t_body_acc_mag_mean"                    
  - "t_gravity_acc_mag_mean"                  
  - "t_body_acc_jerk_mag_mean"                
  - "t_body_gyro_mag_mean"                   
  - "t_body_gyro_jerk_mag_mean"               
  - "f_body_acc_mean_x"                       
  - "f_body_acc_mean_y"                      
  - "f_body_acc_mean_z"                       
  - "f_body_acc_mean_freq_x"                  
  - "f_body_acc_mean_freq_y"                 
  - "f_body_acc_mean_freq_z"                  
  - "f_body_acc_jerk_mean_x"                  
  - "f_body_acc_jerk_mean_y"                 
  - "f_body_acc_jerk_mean_z"                  
  - "f_body_acc_jerk_mean_freq_x"             
  - "f_body_acc_jerk_mean_freq_y"            
  - "f_body_acc_jerk_mean_freq_z"             
  - "f_body_gyro_mean_x"                      
  - "f_body_gyro_mean_y"                     
  - "f_body_gyro_mean_z"                      
  - "f_body_gyro_mean_freq_x"                 
  - "f_body_gyro_mean_freq_y"                
  - "f_body_gyro_mean_freq_z"                 
  - "f_body_acc_mag_mean"                     
  - "f_body_acc_mag_mean_freq"               
  - "f_body_body_acc_jerk_mag_mean"           
  - "f_body_body_acc_jerk_mag_mean_freq"      
  - "f_body_body_gyro_mag_mean"              
  - "f_body_body_gyro_mag_mean_freq"          
  - "f_body_body_gyro_jerk_mag_mean"          
  - "f_body_body_gyro_jerk_mag_mean_freq"    
  - "anglet_body_acc_mean_gravity"            
  - "anglet_body_acc_jerk_mean_gravity_mean"  
  - "anglet_body_gyro_mean_gravity_mean"     
  - "anglet_body_gyro_jerk_mean_gravity_mean" 
  - "anglex_gravity_mean"                     
  - "angley_gravity_mean"                    
  - "anglez_gravity_mean"                     
  - "t_body_acc_std_x"                        
  - "t_body_acc_std_y"                       
  - "t_body_acc_std_z"                        
  - "t_gravity_acc_std_x"                     
  - "t_gravity_acc_std_y"                    
  - "t_gravity_acc_std_z"                     
  - "t_body_acc_jerk_std_x"                   
  - "t_body_acc_jerk_std_y"                  
  - "t_body_acc_jerk_std_z"                   
  - "t_body_gyro_std_x"                       
  - "t_body_gyro_std_y"                      
  - "t_body_gyro_std_z"                       
  - "t_body_gyro_jerk_std_x"                  
  - "t_body_gyro_jerk_std_y"                 
  - "t_body_gyro_jerk_std_z"                  
  - "t_body_acc_mag_std"                     
  - "t_gravity_acc_mag_std"                  
  - "t_body_acc_jerk_mag_std"                 
  - "t_body_gyro_mag_std"                     
  - "t_body_gyro_jerk_mag_std"               
  - "f_body_acc_std_x"                        
  - "f_body_acc_std_y"                        
  - "f_body_acc_std_z"                       
  - "f_body_acc_jerk_std_x"                   
  - "f_body_acc_jerk_std_y"                   
  - "f_body_acc_jerk_std_z"                  
  - "f_body_gyro_std_x"                       
  - "f_body_gyro_std_y"                       
  - "f_body_gyro_std_z"                      
  - "f_body_acc_mag_std"                      
  - "f_body_body_acc_jerk_mag_std"            
  - "f_body_body_gyro_mag_std"               
  - "f_body_body_gyro_jerk_mag_std"
  
## Process of Tidying the Dataset

1. Renamed features to be a little neater
1. Insert features list as column names for test and train sets
1. Change labels to be actual activity names
1. Insert activity names as columns in test and train sets
1. Remove duplicate columns from test and train sets
1. Merge test and train sets
1. Select only subject, activity, and columns containing "mean" and "std" for measurements on the mean and standard deviation
1. Find the Mean by subject and activity on all measurements
1. Saved dataset as tidy.txt